// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cycloidio/sentry-plugin/issue (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/issue_repository.go -mock_names=Repository=IssueRepository -package mock github.com/cycloidio/sentry-plugin/issue Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	issue "github.com/cycloidio/sentry-plugin/issue"
	gomock "go.uber.org/mock/gomock"
)

// IssueRepository is a mock of Repository interface.
type IssueRepository struct {
	ctrl     *gomock.Controller
	recorder *IssueRepositoryMockRecorder
	isgomock struct{}
}

// IssueRepositoryMockRecorder is the mock recorder for IssueRepository.
type IssueRepositoryMockRecorder struct {
	mock *IssueRepository
}

// NewIssueRepository creates a new mock instance.
func NewIssueRepository(ctrl *gomock.Controller) *IssueRepository {
	mock := &IssueRepository{ctrl: ctrl}
	mock.recorder = &IssueRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *IssueRepository) EXPECT() *IssueRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *IssueRepository) Create(ctx context.Context, orgSlug, prjSlug string, i issue.Issue) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, orgSlug, prjSlug, i)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *IssueRepositoryMockRecorder) Create(ctx, orgSlug, prjSlug, i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*IssueRepository)(nil).Create), ctx, orgSlug, prjSlug, i)
}

// Delete mocks base method.
func (m *IssueRepository) Delete(ctx context.Context, orgSlug, prjSlug, isuID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, orgSlug, prjSlug, isuID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *IssueRepositoryMockRecorder) Delete(ctx, orgSlug, prjSlug, isuID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*IssueRepository)(nil).Delete), ctx, orgSlug, prjSlug, isuID)
}

// Filter mocks base method.
func (m *IssueRepository) Filter(ctx context.Context, orgSlug, prjSlug string) ([]*issue.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx, orgSlug, prjSlug)
	ret0, _ := ret[0].([]*issue.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *IssueRepositoryMockRecorder) Filter(ctx, orgSlug, prjSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*IssueRepository)(nil).Filter), ctx, orgSlug, prjSlug)
}

// Find mocks base method.
func (m *IssueRepository) Find(ctx context.Context, orgSlug, prjSlug, isuID string) (*issue.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, orgSlug, prjSlug, isuID)
	ret0, _ := ret[0].(*issue.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *IssueRepositoryMockRecorder) Find(ctx, orgSlug, prjSlug, isuID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*IssueRepository)(nil).Find), ctx, orgSlug, prjSlug, isuID)
}

// Update mocks base method.
func (m *IssueRepository) Update(ctx context.Context, orgSlug, prjSlug, isuID string, i issue.Issue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, orgSlug, prjSlug, isuID, i)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *IssueRepositoryMockRecorder) Update(ctx, orgSlug, prjSlug, isuID, i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*IssueRepository)(nil).Update), ctx, orgSlug, prjSlug, isuID, i)
}
