// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cycloidio/sentry-plugin/issue (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/issue_repository.go -mock_names=Repository=IssueRepository -package mock github.com/cycloidio/sentry-plugin/issue Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	issue "github.com/cycloidio/sentry-plugin/issue"
	gomock "go.uber.org/mock/gomock"
)

// IssueRepository is a mock of Repository interface.
type IssueRepository struct {
	ctrl     *gomock.Controller
	recorder *IssueRepositoryMockRecorder
	isgomock struct{}
}

// IssueRepositoryMockRecorder is the mock recorder for IssueRepository.
type IssueRepositoryMockRecorder struct {
	mock *IssueRepository
}

// NewIssueRepository creates a new mock instance.
func NewIssueRepository(ctrl *gomock.Controller) *IssueRepository {
	mock := &IssueRepository{ctrl: ctrl}
	mock.recorder = &IssueRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *IssueRepository) EXPECT() *IssueRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *IssueRepository) Create(ctx context.Context, orgSlug, prjSlug string, i issue.Issue) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, orgSlug, prjSlug, i)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *IssueRepositoryMockRecorder) Create(ctx, orgSlug, prjSlug, i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*IssueRepository)(nil).Create), ctx, orgSlug, prjSlug, i)
}

// ListAll mocks base method.
func (m *IssueRepository) ListAll(ctx context.Context) ([]issue.IssueWithRelations, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx)
	ret0, _ := ret[0].([]issue.IssueWithRelations)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *IssueRepositoryMockRecorder) ListAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*IssueRepository)(nil).ListAll), ctx)
}
