// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cycloidio/sentry-plugin/organization (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/organization_repository.go -mock_names=Repository=OrganizationRepository -package mock github.com/cycloidio/sentry-plugin/organization Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	organization "github.com/cycloidio/sentry-plugin/organization"
	gomock "go.uber.org/mock/gomock"
)

// OrganizationRepository is a mock of Repository interface.
type OrganizationRepository struct {
	ctrl     *gomock.Controller
	recorder *OrganizationRepositoryMockRecorder
	isgomock struct{}
}

// OrganizationRepositoryMockRecorder is the mock recorder for OrganizationRepository.
type OrganizationRepositoryMockRecorder struct {
	mock *OrganizationRepository
}

// NewOrganizationRepository creates a new mock instance.
func NewOrganizationRepository(ctrl *gomock.Controller) *OrganizationRepository {
	mock := &OrganizationRepository{ctrl: ctrl}
	mock.recorder = &OrganizationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *OrganizationRepository) EXPECT() *OrganizationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *OrganizationRepository) Create(ctx context.Context, o organization.Organization) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, o)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *OrganizationRepositoryMockRecorder) Create(ctx, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*OrganizationRepository)(nil).Create), ctx, o)
}

// Delete mocks base method.
func (m *OrganizationRepository) Delete(ctx context.Context, orgSlug string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, orgSlug)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *OrganizationRepositoryMockRecorder) Delete(ctx, orgSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*OrganizationRepository)(nil).Delete), ctx, orgSlug)
}

// DeleteAll mocks base method.
func (m *OrganizationRepository) DeleteAll(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAll indicates an expected call of DeleteAll.
func (mr *OrganizationRepositoryMockRecorder) DeleteAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*OrganizationRepository)(nil).DeleteAll), ctx)
}

// Filter mocks base method.
func (m *OrganizationRepository) Filter(ctx context.Context) ([]*organization.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx)
	ret0, _ := ret[0].([]*organization.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *OrganizationRepositoryMockRecorder) Filter(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*OrganizationRepository)(nil).Filter), ctx)
}

// Find mocks base method.
func (m *OrganizationRepository) Find(ctx context.Context, orgSlug string) (*organization.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, orgSlug)
	ret0, _ := ret[0].(*organization.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *OrganizationRepositoryMockRecorder) Find(ctx, orgSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*OrganizationRepository)(nil).Find), ctx, orgSlug)
}

// Update mocks base method.
func (m *OrganizationRepository) Update(ctx context.Context, orgSlug string, o organization.Organization) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, orgSlug, o)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *OrganizationRepositoryMockRecorder) Update(ctx, orgSlug, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*OrganizationRepository)(nil).Update), ctx, orgSlug, o)
}
