// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cycloidio/sentry-plugin/project (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/project_repository.go -mock_names=Repository=ProjectRepository -package mock github.com/cycloidio/sentry-plugin/project Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	project "github.com/cycloidio/sentry-plugin/project"
	gomock "go.uber.org/mock/gomock"
)

// ProjectRepository is a mock of Repository interface.
type ProjectRepository struct {
	ctrl     *gomock.Controller
	recorder *ProjectRepositoryMockRecorder
	isgomock struct{}
}

// ProjectRepositoryMockRecorder is the mock recorder for ProjectRepository.
type ProjectRepositoryMockRecorder struct {
	mock *ProjectRepository
}

// NewProjectRepository creates a new mock instance.
func NewProjectRepository(ctrl *gomock.Controller) *ProjectRepository {
	mock := &ProjectRepository{ctrl: ctrl}
	mock.recorder = &ProjectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *ProjectRepository) EXPECT() *ProjectRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *ProjectRepository) Create(ctx context.Context, orgSlug string, p project.Project) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, orgSlug, p)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *ProjectRepositoryMockRecorder) Create(ctx, orgSlug, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*ProjectRepository)(nil).Create), ctx, orgSlug, p)
}

// Delete mocks base method.
func (m *ProjectRepository) Delete(ctx context.Context, orgSlug, prjSlug string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, orgSlug, prjSlug)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *ProjectRepositoryMockRecorder) Delete(ctx, orgSlug, prjSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*ProjectRepository)(nil).Delete), ctx, orgSlug, prjSlug)
}

// Filter mocks base method.
func (m *ProjectRepository) Filter(ctx context.Context, orgSlug string) ([]*project.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx, orgSlug)
	ret0, _ := ret[0].([]*project.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *ProjectRepositoryMockRecorder) Filter(ctx, orgSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*ProjectRepository)(nil).Filter), ctx, orgSlug)
}

// Find mocks base method.
func (m *ProjectRepository) Find(ctx context.Context, orgSlug, prjSlug string) (*project.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, orgSlug, prjSlug)
	ret0, _ := ret[0].(*project.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *ProjectRepositoryMockRecorder) Find(ctx, orgSlug, prjSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*ProjectRepository)(nil).Find), ctx, orgSlug, prjSlug)
}

// Update mocks base method.
func (m *ProjectRepository) Update(ctx context.Context, orgSlug, prjSlug string, p project.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, orgSlug, prjSlug, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *ProjectRepositoryMockRecorder) Update(ctx, orgSlug, prjSlug, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*ProjectRepository)(nil).Update), ctx, orgSlug, prjSlug, p)
}
