// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cycloidio/sentry-plugin/sentry (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=../mock/sentry_service.go -mock_names=Service=SentryService -package mock github.com/cycloidio/sentry-plugin/sentry Service
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	sentry "github.com/atlassian/go-sentry-api"
	gomock "go.uber.org/mock/gomock"
)

// SentryService is a mock of Service interface.
type SentryService struct {
	ctrl     *gomock.Controller
	recorder *SentryServiceMockRecorder
	isgomock struct{}
}

// SentryServiceMockRecorder is the mock recorder for SentryService.
type SentryServiceMockRecorder struct {
	mock *SentryService
}

// NewSentryService creates a new mock instance.
func NewSentryService(ctrl *gomock.Controller) *SentryService {
	mock := &SentryService{ctrl: ctrl}
	mock.recorder = &SentryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *SentryService) EXPECT() *SentryServiceMockRecorder {
	return m.recorder
}

// GetIssues mocks base method.
func (m *SentryService) GetIssues(o sentry.Organization, p sentry.Project, statsPeriod *string, shortIDLookup *bool, query *string) ([]sentry.Issue, *sentry.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIssues", o, p, statsPeriod, shortIDLookup, query)
	ret0, _ := ret[0].([]sentry.Issue)
	ret1, _ := ret[1].(*sentry.Link)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetIssues indicates an expected call of GetIssues.
func (mr *SentryServiceMockRecorder) GetIssues(o, p, statsPeriod, shortIDLookup, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIssues", reflect.TypeOf((*SentryService)(nil).GetIssues), o, p, statsPeriod, shortIDLookup, query)
}

// GetOrgProjects mocks base method.
func (m *SentryService) GetOrgProjects(o sentry.Organization) ([]sentry.Project, *sentry.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrgProjects", o)
	ret0, _ := ret[0].([]sentry.Project)
	ret1, _ := ret[1].(*sentry.Link)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetOrgProjects indicates an expected call of GetOrgProjects.
func (mr *SentryServiceMockRecorder) GetOrgProjects(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrgProjects", reflect.TypeOf((*SentryService)(nil).GetOrgProjects), o)
}

// GetOrganization mocks base method.
func (m *SentryService) GetOrganization(orgslug string) (sentry.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganization", orgslug)
	ret0, _ := ret[0].(sentry.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganization indicates an expected call of GetOrganization.
func (mr *SentryServiceMockRecorder) GetOrganization(orgslug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganization", reflect.TypeOf((*SentryService)(nil).GetOrganization), orgslug)
}

// GetOrganizations mocks base method.
func (m *SentryService) GetOrganizations() ([]sentry.Organization, *sentry.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizations")
	ret0, _ := ret[0].([]sentry.Organization)
	ret1, _ := ret[1].(*sentry.Link)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetOrganizations indicates an expected call of GetOrganizations.
func (mr *SentryServiceMockRecorder) GetOrganizations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizations", reflect.TypeOf((*SentryService)(nil).GetOrganizations))
}
