// Code generated by "enumer -type=Color -linecomment -transform=lower -json -output=color_enumer_gen.go"; DO NOT EDIT.

package event

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ColorName = "blacksilvergraywhitemaroonredpurplefuchsiagreenlimeoliveyellownavybluetealaquaorange"

var _ColorIndex = [...]uint8{0, 0, 5, 11, 15, 20, 26, 29, 35, 42, 47, 51, 56, 62, 66, 70, 74, 78, 84}

const _ColorLowerName = "blacksilvergraywhitemaroonredpurplefuchsiagreenlimeoliveyellownavybluetealaquaorange"

func (i Color) String() string {
	if i >= Color(len(_ColorIndex)-1) {
		return fmt.Sprintf("Color(%d)", i)
	}
	return _ColorName[_ColorIndex[i]:_ColorIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ColorNoOp() {
	var x [1]struct{}
	_ = x[NoColor-(0)]
	_ = x[Black-(1)]
	_ = x[Silver-(2)]
	_ = x[Gray-(3)]
	_ = x[White-(4)]
	_ = x[Maroon-(5)]
	_ = x[Red-(6)]
	_ = x[Purple-(7)]
	_ = x[Fuchsia-(8)]
	_ = x[Green-(9)]
	_ = x[Lime-(10)]
	_ = x[Olive-(11)]
	_ = x[Yellow-(12)]
	_ = x[Navy-(13)]
	_ = x[Blue-(14)]
	_ = x[Teal-(15)]
	_ = x[Aqua-(16)]
	_ = x[Orange-(17)]
}

var _ColorValues = []Color{NoColor, Black, Silver, Gray, White, Maroon, Red, Purple, Fuchsia, Green, Lime, Olive, Yellow, Navy, Blue, Teal, Aqua, Orange}

var _ColorNameToValueMap = map[string]Color{
	_ColorName[0:0]:        NoColor,
	_ColorLowerName[0:0]:   NoColor,
	_ColorName[0:5]:        Black,
	_ColorLowerName[0:5]:   Black,
	_ColorName[5:11]:       Silver,
	_ColorLowerName[5:11]:  Silver,
	_ColorName[11:15]:      Gray,
	_ColorLowerName[11:15]: Gray,
	_ColorName[15:20]:      White,
	_ColorLowerName[15:20]: White,
	_ColorName[20:26]:      Maroon,
	_ColorLowerName[20:26]: Maroon,
	_ColorName[26:29]:      Red,
	_ColorLowerName[26:29]: Red,
	_ColorName[29:35]:      Purple,
	_ColorLowerName[29:35]: Purple,
	_ColorName[35:42]:      Fuchsia,
	_ColorLowerName[35:42]: Fuchsia,
	_ColorName[42:47]:      Green,
	_ColorLowerName[42:47]: Green,
	_ColorName[47:51]:      Lime,
	_ColorLowerName[47:51]: Lime,
	_ColorName[51:56]:      Olive,
	_ColorLowerName[51:56]: Olive,
	_ColorName[56:62]:      Yellow,
	_ColorLowerName[56:62]: Yellow,
	_ColorName[62:66]:      Navy,
	_ColorLowerName[62:66]: Navy,
	_ColorName[66:70]:      Blue,
	_ColorLowerName[66:70]: Blue,
	_ColorName[70:74]:      Teal,
	_ColorLowerName[70:74]: Teal,
	_ColorName[74:78]:      Aqua,
	_ColorLowerName[74:78]: Aqua,
	_ColorName[78:84]:      Orange,
	_ColorLowerName[78:84]: Orange,
}

var _ColorNames = []string{
	_ColorName[0:0],
	_ColorName[0:5],
	_ColorName[5:11],
	_ColorName[11:15],
	_ColorName[15:20],
	_ColorName[20:26],
	_ColorName[26:29],
	_ColorName[29:35],
	_ColorName[35:42],
	_ColorName[42:47],
	_ColorName[47:51],
	_ColorName[51:56],
	_ColorName[56:62],
	_ColorName[62:66],
	_ColorName[66:70],
	_ColorName[70:74],
	_ColorName[74:78],
	_ColorName[78:84],
}

// ColorString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ColorString(s string) (Color, error) {
	if val, ok := _ColorNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ColorNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Color values", s)
}

// ColorValues returns all values of the enum
func ColorValues() []Color {
	return _ColorValues
}

// ColorStrings returns a slice of all String values of the enum
func ColorStrings() []string {
	strs := make([]string, len(_ColorNames))
	copy(strs, _ColorNames)
	return strs
}

// IsAColor returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Color) IsAColor() bool {
	for _, v := range _ColorValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Color
func (i Color) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Color
func (i *Color) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Color should be a string, got %s", data)
	}

	var err error
	*i, err = ColorString(s)
	return err
}
