// Code generated by "enumer -type=Severity -transform=snake -json -output=severity_enumer_gen.go"; DO NOT EDIT.

package event

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _SeverityName = "infowarnerrcrit"

var _SeverityIndex = [...]uint8{0, 4, 8, 11, 15}

const _SeverityLowerName = "infowarnerrcrit"

func (i Severity) String() string {
	i -= 1
	if i >= Severity(len(_SeverityIndex)-1) {
		return fmt.Sprintf("Severity(%d)", i+1)
	}
	return _SeverityName[_SeverityIndex[i]:_SeverityIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SeverityNoOp() {
	var x [1]struct{}
	_ = x[Info-(1)]
	_ = x[Warn-(2)]
	_ = x[Err-(3)]
	_ = x[Crit-(4)]
}

var _SeverityValues = []Severity{Info, Warn, Err, Crit}

var _SeverityNameToValueMap = map[string]Severity{
	_SeverityName[0:4]:        Info,
	_SeverityLowerName[0:4]:   Info,
	_SeverityName[4:8]:        Warn,
	_SeverityLowerName[4:8]:   Warn,
	_SeverityName[8:11]:       Err,
	_SeverityLowerName[8:11]:  Err,
	_SeverityName[11:15]:      Crit,
	_SeverityLowerName[11:15]: Crit,
}

var _SeverityNames = []string{
	_SeverityName[0:4],
	_SeverityName[4:8],
	_SeverityName[8:11],
	_SeverityName[11:15],
}

// SeverityString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SeverityString(s string) (Severity, error) {
	if val, ok := _SeverityNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SeverityNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Severity values", s)
}

// SeverityValues returns all values of the enum
func SeverityValues() []Severity {
	return _SeverityValues
}

// SeverityStrings returns a slice of all String values of the enum
func SeverityStrings() []string {
	strs := make([]string, len(_SeverityNames))
	copy(strs, _SeverityNames)
	return strs
}

// IsASeverity returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Severity) IsASeverity() bool {
	for _, v := range _SeverityValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Severity
func (i Severity) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Severity
func (i *Severity) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Severity should be a string, got %s", data)
	}

	var err error
	*i, err = SeverityString(s)
	return err
}
